INSERT INTO ders (DersAdi) VALUES 
('matematik1'), 
('matematik2'), 
('fizik1'), 
('fizik2'), 
('algoritma ve programlama'), 
('nesne tabanlý programlama'), 
('veri yapýlarý'), 
('ayrýk matematik'), 
('diferansiyel denklemler'), 
('lineer cebir'), 
('sayýsal analiz'), 
('otomata teorisi'), 
('programlama dilleri'), 
('algoritma analizi'), 
('sinyaller sistemler'), 
('bilgisayar mimarisi'), 
('mikroiþlemciler'), 
('iþletim sistemleri'), 
('gömülü sistemler'), 
('optimizasyon'), 
('mobil programlama'), 
('robot programlama'), 
('yazýlým mühendisliði'), 
('veritabaný tasarým1'), 
('veritabaný tasarým2'), 
('yapay zekaya giriþ'), 
('mühendislik ekonomisi'), 
('olasýlýk ve istatistik'), 
('yazýlým test ve doðrulama'), 
('görüntü iþleme'), 
('internet teknolojileri'), 
('mesleki ingilizce1'), 
('mesleki ingilizce2'), 
('siber güvenlik'), 
('bilgisayar aðlarý'), 
('bulut biliþim'), 
('makine öðrenmesi'), 
('veri madenciliði'), 
('nesnelerin interneti'), 
('iþ güvenliði ve saðlýðý1'), 
('iþ güvenliði ve saðlýðý2'), 
('sayýsal elektronik'), 
('bilgisayar bilimlerine giriþ'), 
('görsel programlama'), 
('bitirme ödevi'), 
('veri bilimi'), 
('ses iþleme ve tanýma'), 
('eþ zamanlý programlama'), 
('paralel programlama');
('bilgisayar güvenliði');

select count(*) from ders
select * from ders